Templates_Project/BasicApp/urls.py
from django.urls import path,include
from BasicApp import views


app_name = 'BasicApp'

urlpatterns = [
    path('other/',views.other,name='other'),
    path('relative/',views.relative,name='relative'),
]

Templates_Project/Templates_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from BasicApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('BasicApp/',include('BasicApp.urls')),
]

Templates_Project/BasicApp/models.py
from django.db import models

# Create your models here.

Templates_Project/BasicApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'Hello World','number':100}
    return render(request,'BasicApp/index.html',context_dict)

def other(request):
    return render(request,'BasicApp/other.html')

def relative(request):
    return render(request,'BasicApp/relative.html')

Templates_Project/templates/BasicApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <!-- <nav class = 'navbar navbar-default navbar-static-top'>
        <div class ='container'>
            <ul class='nav navbar-nav'>
                <li><a class='navbar-brand' href=""></a>Brand</li>
                <li><a class='navbar-link' href=""></a>Admin</li>
                <li><a class='navbar-link' href=""></a>Other</li>

            </ul>
        </div>

    </nav>  -->
    
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="index">
        <img src="{% static 'logo.png' %}" alt="Logo" style="width:40px;">
    </a>
    
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">
            Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'BasicApp:other' %}">Other</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'BasicApp:relative' %}">Relative</a>
      </li>
    </ul>
  </nav>

    <div class='container'>
        {% block body_block %}

 <!-- not gonna inherited -->
        {% endblock %}
    </div>

    
</body>
</html>

Templates_Project/templates/BasicApp/index.html
<!DOCTYPE html>
{% extends "BasicApp/base.html" %}
    <h1>This is Index Page</h1>
    {% block body_block%}
    <h1>This is the index page</h1>
    <h1>{{ text|cut:'o' }}</h1>
    <h1>{{number|add:'99'}}</h1>
    {% endblock %}

Templates_Project/templates/BasicApp/other.html
<!DOCTYPE html>
{% extends 'BasicApp/base.html' %}
    {% block body-block%}
    <h1>This is Other</h1>

    {% endblock %}

Templates_Project/templates/BasicApp/relative.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Relative</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <h1>This is Relative</h1>
    <a href="{% url 'BasicApp:other' %}">The Other Page</a>
    <a href="{% url 'admin:index' %}">Go to Admin</a>
    <a href="{% url 'index' %}">Back to Index</a>
</body>
</html>